### ISSUE TITLE
The app crashes when flipping through the book in the battlefield with spell book animation enabled

### ISSUE THREAD

**Issue by lishaoxia1985** [vcmi-mods/chinese-translation#13]
@misiokles This bug appears only when the Chinese translation mod is enabled. So we should fix this mod.

**Comment by misiokles** [comment]
I don't know how to fix :(

**Comment by lishaoxia1985** [comment]
@misiokles I have test it again. The bug appears not only on battlefield. You can test other language mod. If the bug appears again, we can create an issue on Vcmi project.

**Comment by lishaoxia1985** [comment]
@misiokles I have test polish translation mod. The bug appears again. I have create issue vcmi/vcmi#5043

**Comment by lishaoxia1985** [comment]
Fixes vcmi/vcmi#5046

**Comment by lishaoxia1985** [comment]
Fixed by vcmi/vcmi#5046
