### ISSUE TITLE
Replacing pcx with png make the text unclear

### ISSUE THREAD

**Issue by lishaoxia1985** [vcmi-mods/chinese-translation#3]
@heroesiiifan you can look at this:
![Screenshot_20230805_091300_is.xyz.vcmi.daily.jpg](https://github.com/vcmi-mods/chinese-translation/assets/49801619/2a3a2f55-661d-4db7-bb62-531615559c78)

BY the way, the "单人场景" button in the picture below have an edge or a contour, it should be edited to remove the edge or  contour.
![Screenshot_20230805_091440_is.xyz.vcmi.daily.jpg](https://github.com/vcmi-mods/chinese-translation/assets/49801619/4aa7a643-64a0-46a9-ba29-0df0ba0d6e76)

**Comment by heroesiiifan** [comment]
Thanks for the information.

Will have a look...

**Comment by lishaoxia1985** [comment]
@heroesiiifan In fact, other button such as "最高得分" also have the same problem as "单人场景".
Maybe we can use tradition Chinese button.

**Comment by heroesiiifan** [comment]
Unclear text should be fixed. VCMI has some problems with indexed PNGs. Have to fix it in other translations as well.

**Just for reference:**
Used Imagemagick to convert: `for i in *.bmp ; do convert "$i" "${i%.*}.png" ; done` (bmp or pcx)
And afterwards converted indexed pngs to RGB24: `for i in *.png ; do convert "$i" PNG24:"${i%.*}.png" ; done` (can be done in one step)

@lishaoxia1985 Yes, I know. But it's not easy to fix. If you find some other better matching images: no problem, we can change them. But it's not easy for non chinese people to find it (language barrier and some files could not be downloaded outside china).
